name: ESP32 Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up ESP-IDF
        uses: espressif/setup-idf@v2.8
        with:
          version: v5.1

      - name: Install dependencies
        run: idf.py install

      - name: Build the firmware
        run: idf.py build

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp32-bin
          path: build/*.bin

