name: Build ESP32 Firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/setup-idf@v1
        with:
          version: v5.1

      - name: Build firmware
        run: |
          . $IDF_PATH/export.sh
          idf.py build
        working-directory: .

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: build/*.bin
