name: ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Clone ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
        cd ~/esp-idf
        ./install.sh

    - name: Build Project
      run: |
        . ~/esp-idf/export.sh
        idf.py build
      working-directory: src

    - name: Upload firmware binaries
      uses: actions/upload-artifact@v3
      with:
        name: esp32-build-artifacts
        path: src/build/
